### ISSUE TITLE
Cluster Init example fails

### ISSUE THREAD

**Issue by UzLA** [brianshumate/ansible-couchbase-server#30]
Running vagrant up from examples folder fails after basic build of 3 boxes but before provisioning couchbase (fresh Git ansible-couchbase-server clone, fresh host ubuntu 14.04 install. BOX_NAME="ubuntu/trusty64" CLUSTER_HOSTS="ubuntu" vagrant up fails with the same error) : 
ERROR: cannot find role in /home/uzla/Vagrant/ansible-couchbase-server/examples/roles/couchbase.couchbase-server or /home/uzla/Vagrant/ansible-couchbase-server/examples/couchbase.couchbase-server or /etc/ansible/roles/couchbase.couchbase-server
Ansible failed to complete successfully. Any error output should be visible above. Please fix these errors and try again.

examples/bin/preinstall run successfully updating /etc/hosts appropriately before running vagrant up.

Failure happens after node3 basic provisioning;
==> node3: Machine booted and ready!
==> node3: Checking for guest additions in VM...
==> node3: Checking for host entries
==> node3: adding to (/etc/hosts) : 10.1.42.30 node3.local # VAGRANT: f9f7a12bf23d832652d349858fe0b44a (node3) / 9ee3de21-c12c-4343-a120-0cb03df692a9
==> node3: Setting hostname...
==> node3: Configuring and enabling network interfaces...
==> node3: Mounting shared folders...
node3: /vagrant => /home/uzla/Vagrant/ansible-couchbase-server/examples
==> node3: Running provisioner: hosts...
==> node3: Running provisioner: ansible...
PYTHONUNBUFFERED=1 ANSIBLE_FORCE_COLOR=true ANSIBLE_HOST_KEY_CHECKING=false ANSIBLE_SSH_ARGS='-o UserKnownHostsFile=/dev/null -o ForwardAgent=yes -o ControlMaster=auto -o ControlPersist=60s' ansible-playbook --private-key=/home/uzla/Vagrant/ansible-couchbase-server/examples/.vagrant/machines/node3/virtualbox/private_key --user=vagrant --connection=ssh --limit='all' --inventory-file=centos --extra-vars={"couchbase_server_ram":1024} cluster_init.yml
ERROR: cannot find role in /home/uzla/Vagrant/ansible-couchbase-server/examples/roles/couchbase.couchbase-server or /home/uzla/Vagrant/ansible-couchbase-server/examples/couchbase.couchbase-server or /etc/ansible/roles/couchbase.couchbase-server
Ansible failed to complete successfully. Any error output should be visible above. Please fix these errors and try again.

Would someone have any ideas?

**Comment by brianshumate** [comment]
Hi,

This role is designed to be installed via the `ansible-galaxy` command instead of being directly run from this git repository. Installing it that way should resolve your issue:

```
ansible-galaxy install couchbase.couchbase-server
```

You'll want to make sure you have write access to `/etc/ansible` since that is where the role will be installed by default, or define your own Ansible role path by creating a `$HOME/.ansible.cfg` file with these contents:

```
[defaults]
roles_path <path_to_your_preferred_role_location>
```
Change `<path_to_your_preferred_role_location>` to a directory you have write access to.

Then you can do:

```
cd <path_to_your_preferred_role_location>/couchbase.couchbase-server/examples
vagrant up
```

I will update the documentation to reflect this.

**Comment by UzLA** [comment]
The advice worked like a charm! Thanks a lot!
Although it seems to be a need for a correction to the documentation, as ansible.cfg content is missing "=" symbol: 
[defaults]
roles_path = \<path_to_your_preferred_role_location>

**Comment by brianshumate** [comment]
Ah, yes I overlooked that and will make sure it's correct when I update the docs.

Thanks for your feedback!

**Comment by brianshumate** [comment]
Documentation has been updated. Thanks again for the great feedback. :)

**Comment by UzLA** [comment]
I'm glad to help.

Good job any big thanks for the great software!
